// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3KXAnL_I4P3hFo4PhC_TjLVtA_6yNOA',
    appId: '1:435580013224:web:13384c1df7603becf2909d',
    messagingSenderId: '435580013224',
    projectId: 'uas-ambw-c0051',
    authDomain: 'uas-ambw-c0051.firebaseapp.com',
    storageBucket: 'uas-ambw-c0051.firebasestorage.app',
    measurementId: 'G-W117MW2LFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5bHRA-ZQaGsQVfVZL5N18pzn3BM9INe8',
    appId: '1:435580013224:android:7c9520828309b47bf2909d',
    messagingSenderId: '435580013224',
    projectId: 'uas-ambw-c0051',
    storageBucket: 'uas-ambw-c0051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFEMySdmvZZf4XE-M3m6SRIBYjotiC9Ac',
    appId: '1:435580013224:ios:b280dc1aa086d89ef2909d',
    messagingSenderId: '435580013224',
    projectId: 'uas-ambw-c0051',
    storageBucket: 'uas-ambw-c0051.firebasestorage.app',
    iosBundleId: 'com.example.ambwUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFEMySdmvZZf4XE-M3m6SRIBYjotiC9Ac',
    appId: '1:435580013224:ios:b280dc1aa086d89ef2909d',
    messagingSenderId: '435580013224',
    projectId: 'uas-ambw-c0051',
    storageBucket: 'uas-ambw-c0051.firebasestorage.app',
    iosBundleId: 'com.example.ambwUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi3KXAnL_I4P3hFo4PhC_TjLVtA_6yNOA',
    appId: '1:435580013224:web:4d5abeeaef7a9de1f2909d',
    messagingSenderId: '435580013224',
    projectId: 'uas-ambw-c0051',
    authDomain: 'uas-ambw-c0051.firebaseapp.com',
    storageBucket: 'uas-ambw-c0051.firebasestorage.app',
    measurementId: 'G-1ZPKQH76LN',
  );
}
